# Изключения (Exceptions)

Всеки път, когато използвате някой софтуер (било той уеб базиран или локален на устройството), от вашата гледна точка всичко може да върви гладко. Ако погледнет зад колисите, обаче, понякога може дори да ви се доплаче (хаха, тука имаше рима :Д). 

В много случаи програмата иска да изпълни нещо, но поради една или друга причина това не може да се случи, при което възниква грешка. С цел да продължи нормално работата си, софтуерът трябва да се погрижи за този случай, в който по принцип не сме искали да попаднем (да направим изключение за него).

Нека разгледаме конкретен пример. Разработвате програма, в която потребителят иска да отвори даден файл. Файлът, за съжаление, се оказва, че не съществува. Ако не се погрижим за този случай, програмата ще се счупи. Вместо да прекратява работата си, тя може да изведе съобщение към потребителя и да му каже, че файлът липсва.


## Изключения в Python
Докато пишем нашите скриптове, доста често възникват грешки в програмата. 

Някои от тях са от неправилен синтаксис:
```python
>>> if a < 3
  File "<interactive input>", line 1
    if a < 3
           ^
SyntaxError: invalid syntax
```

Други от невалидна операция:
```python
>>> 1 / 0
Traceback (most recent call last):
 File "<string>", line 301, in runcode
 File "<interactive input>", line 1, in <module>
ZeroDivisionError: division by zero
```

Или пък, както е споменато по-горе, се опитваме да отворим файл, който не съществува:
```python
open("imaginary.txt")
Traceback (most recent call last):
 File "<string>", line 301, in runcode
 File "<interactive input>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'imaginary.txt'
```

Тези грешки възникват докато се изпълнява програмата (runtime). Всеки път, когато възникне такава грешка, Python създава т. нар. `exception` обект. Ако не сме се погрижили за за случая, се извежда съобщение за грешката, заедно с кратки детайли относно как грешката се е получила. Тази информация е предназначена за нас, като програмисти, да разберем какъв е проблемът. Ако се върнем на примера с деленето на нула:
```python
>>> 1 / 0
Traceback (most recent call last):
 File "<string>", line 301, in runcode
 File "<interactive input>", line 1, in <module>
ZeroDivisionError: division by zero
```
виждаме на кой ред е възникнала грешката - `File "<interactive input>", line 1, in <module>` и каква точно е тя - `ZeroDivisionError: division by zero`. 

В Python има набор от вградени грешки (exceptions), които съответстват на определени проблеми в програмата. [Тук](https://docs.python.org/3/library/exceptions.html) можете да видите всичките, заедно с техните описания.
